// generated by server/generateClientFiles.js

let SocketResponses = function(window, undefined) {

let responses = {"success":"success","dbErr":"dbErr","tooHigh":"tooHigh","alreadyExists":"alreadyExists","noExist":"noExist","maxVoxels":"maxVoxels","needDelay":"needDelay","outOfBounds":"outOfBounds"}

function get() {
return responses
}

return {
get: get}

}()